### ISSUE TITLE
Cannot find package error with package requirement

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#104]
Hey,

when trying to update a package which has a new requirement, WoltLab throws the error `Cannot find package` while the required package is included in the uploaded package in the package server.
Manually uploading the same package file works without an error.

**Comment by TimWolla** [comment]
Bundled requirements are ignored when installing from a package server.

**Comment by Sir-Will** [comment]
Ah, so all the requirements need to be available on the package server separately?
Is that the same case for the WoltLab store?

**Comment by TimWolla** [comment]
> Is that the same case for the WoltLab store?

The Plugin Store extracts requirements and optionals to make them available on the package server separately.
