### ISSUE TITLE
basePath and the host header

### ISSUE THREAD

**Issue by sneils** [wbbaddons/Tims-PackageServer#13]
You recently deprecated setting the `basePath` variable in the config file and recommended to rather configure a reverse proxy to add a proper host header.

This creates problems when _not_ running on the root of your domain, e.g.
`http://example.com/package-server/`
By only using the host header and ignoring the base path (`/package-server/`), the server creates wrong URLs for his own resources and back links, rendering it disfunctional.

**Comment by SoftCreatR** [comment]
You can simply do (nginx): `proxy_set_header Host http://example.com/package-server/;`

This is, how i run https://packages.softcreatr.de
