### ISSUE TITLE
HTTPS Fails and also Packages doesnt get listed

### ISSUE THREAD

**Issue by HerrTxbias** [wbbaddons/Tims-PackageServer#17]
Yes, the title says everything. In the Browser (behind a reverse proxy) i get the following error: `Unsafe attempt to load URL on://package.herrtxbias.net/style/main.xslt from frame with URL https://package.herrtxbias.net/. Domains, protocols and ports must match.` 

And when i try to load it directly (http://fra1.server.herrtxbias.me:9001/) i'm getting back, that there are no packages, which is wrong, because i've added one project, like in the tutorial. If somebody has any ideas, just let me know!

**Comment by TimWolla** [comment]
> In the Browser (behind a reverse proxy) i get the following error

What does your configuration look like?

> that there are no packages

Enable debug logging and check the output.

**Comment by HerrTxbias** [comment]
The nginx configuration: 
`server {
    listen 80;
    listen [::]:80;

    server_name package.herrtxbias.net;

    location / {
       proxy_pass http://127.0.0.1:9001/;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $https;
    }

        include php;
        include phpmyadmin;
        include defaults;
        include ssl;
        include status;
        include security;
}`

And the second problem was fixed

**Comment by TimWolla** [comment]
There's a currently undocumented configuration option `trustProxy`. Try setting it to `true`.

**Comment by HerrTxbias** [comment]
Already checked this before. And doesn't help

**Comment by TimWolla** [comment]
You are passing an invalid value as `X-Forwarded-Proto` then.
