### ISSUE TITLE
Auth causing errors

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#30]
I just set up the package server but it keeps throwing the error below:
`Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue`

I tried with `*` and `$v > 1.0.0` but the error stays the same.

```json
{
	"users": {
		"admin": {
			"passwd": "asdklawjido",
			"groups": [ "Administrator" ],
			"packages": {
			}
		}
	},
	"groups": {
		"Administrator": {
			"*": "*"
		}
	}
}
```

**Comment by TimWolla** [comment]
The password hash is not valid. The package server expects a double BCrypt hash as used by WoltLab Suite.

**Comment by Sir-Will** [comment]
Oh, what's the easiest way to generate one without coding it?

**Comment by Sir-Will** [comment]
I generated a hash with https://www.appdevtools.com/bcrypt-generator and then generated another hash with the previous one but the auth doesn't accept the login.

**Comment by TimWolla** [comment]
> I generated a hash with https://www.appdevtools.com/bcrypt-generator and then generated another hash with the previous one but the auth doesn't accept the login.

I assume that tool used a different salt for the second hash. I don't think you can easily generate one without coding. You'll need a bcrypt implementation where you can generate a bcrypt hash with a user specified salt. The `crypt()` function of PHP would do, the `password_*` functions won't.

**Comment by Sir-Will** [comment]
Ok, I created a quick nodejs script and now it works. Thanks for the help.

```javascript
const bcrypt = require('bcrypt');

const saltRounds = 10;
const myPlaintextPassword = 'i0mJwOEc9A0QK4yawKpV3701USo8AYoPCTho40IIYK3oudk5l7mjp7j3sTGHL174';

bcrypt.genSalt(saltRounds, function(err, salt) {
    console.log(salt);
    bcrypt.hash(myPlaintextPassword, salt, function(err, hash) {
        console.log(hash);
        bcrypt.hash(hash, salt, function(err, hash) {
            console.log(hash);
        });
    });
});
```
