### ISSUE TITLE
Breaking issue causing requiredpackage names to get split

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#32]
The `requiredpackage` entries are getting split on uppercase letters for some reason, causing the updating via the package server to error out with invalid requirements.

The package.xml in the plugin:
```xml
<requiredpackages>
	<requiredpackage minversion="5.2.0 RC 1">com.woltlab.wcf</requiredpackage>
	<requiredpackage minversion="5.2.0 RC 1">com.woltlab.wbb</requiredpackage>
	<requiredpackage minversion="5.2.0 RC 1">com.woltlab.wcf.conversation</requiredpackage>
	<requiredpackage minversion="5.2.0">com.cls-design.wcf.layoutExpansionKit</requiredpackage>
</requiredpackages>
```
The resulting output from the Package Server:
```xml
<requiredpackages>
    <requiredpackage minversion="5.2.0 RC 1">com.woltlab.wcf</requiredpackage>
    <requiredpackage minversion="5.2.0 RC 1">com.woltlab.wbb</requiredpackage>
    <requiredpackage minversion="5.2.0 RC 1">com.woltlab.wcf.conversation</requiredpackage>
    <requiredpackage minversion="5.2.0">com.cls-design.wcf.layout</requiredpackage>
    <requiredpackage minversion="5.2.0">ExpansionKit</requiredpackage>
</requiredpackages>
```

**Comment by Sir-Will** [comment]
It didn't like `<license/>` under `packageinformation`, after removing it the requiredpackage was no longer split.

**Comment by TimWolla** [comment]
> It didn't like `<license/>` under `packageinformation`, after removing it the requiredpackage was no longer split.

Can you please provide a package that reproduces the issue? I'd be fine with a PR fixing the issue as well.

**Comment by Sir-Will** [comment]
Does the package server validate the xml file? Validating it for any invalid entries and returning some kind of readable error on installation might be enough (showing up in the ACP if that's possible).

I can look into creating a package for reproduction.

**Comment by TimWolla** [comment]
It does the bare minimum of validation (i.e. checking whether required fields exist).

> showing up in the ACP if that's possible

I don't understand. This package server is a standalone application with no ACP integration.

**Comment by Sir-Will** [comment]
> I don't understand. This package server is a standalone application with no ACP integration.

I'm aware, is it not possible to return an error which WoltLab automatically displays? Like the invalid login or are these all predefined errors?

**Comment by Sir-Will** [comment]
To reproduce the issue it requires a WoltLab installation which can be upgraded and a package which is installed and being upgraded at the same time via this package server.
The package needs to have `<license/>` inside `packageinformation` like below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<package name="com.example.examplepackage" xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/2019/package.xsd">
	<packageinformation>
		<packagename>Example Package</packagename>
		<packagedescription>An Example Package.</packagedescription>
		<version>1.0.0</version>
		<date>2020-03-10</date>
        <license/>
	</packageinformation>

	<authorinformation>
		<author>Author</author>
	</authorinformation>

	<requiredpackages>
		<requiredpackage minversion="5.2.0 RC 1">com.woltlab.wcf</requiredpackage>
	</requiredpackages>

	<excludedpackages>
		<excludedpackage version="6.0.0 Alpha 1">com.woltlab.wcf</excludedpackage>
	</excludedpackages>

	<instructions type="install">
		<instruction type="file">files_wcf.tar</instruction>
	</instructions>
</package>
```
