### ISSUE TITLE
Support gzip packages

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#94]
Hey,
it would be great if gzip packages with the endings `tar.gz` and `t.gz` would be supported.

**Comment by TimWolla** [comment]
Not interested in that, as it would make the `packages/` directory ambiguous.

**Comment by TimWolla** [comment]
> Hm, I don't see how it would make it ambiguous unless the same package keeps switching between tar and gzip between versions, which is unlikely.

Unlikely, but it might happen by accident that a `1.0.0.tar` and `1.0.0.tar.gz` (or `1.0.0.tgz`) is placed in the package directory. It is not clear what the correct behavior would be in this case. Disallowing compression neatly solves that issue. It also avoids needing to deal with compression in the code, thus simplifying the logic and avoiding including another dependency.

**Comment by Sir-Will** [comment]
I get your point, though the amount of reduced file sizes can make it worth.

![](https://i.imgur.com/jIYsSFJ.png)
